---

name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - master
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1"

defaults:
  run:
    working-directory: "de-it-krachten/ansible-playbooks-docker_build"


jobs:

  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Show runner info
        run: |
          hostname -f

      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/

      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

      - name: Install test dependencies.
        run: pip3 install ansible ansible-lint==5.4.0 yamllint jmespath

      - name: Lint code.
        run: |
          set -e
          yamllint .
          ansible-lint
